server:
  port: 8082

spring:
  application:
    name: CARD-STATEMENT-SERVICE


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

  instance:
    hostname: localhost

management:
  endpoint:
  endpoints:
    web:
      exposure:
        include: "*"
